name: CI
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install wheel
        pip install tox
        echo
        which python
        which pip
        which tox
        echo
        python --version
        pip --version
        tox --version
        echo
        pip list

    - name: Test mytemplate python package
      run: |
        tox -r

    - name: Generate coverage for coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tox -r -e coverage,coveralls

