name: GitHub CI Action
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install wheel
        pip install tox
        echo
        which python
        which pip
        which tox
        echo
        python --version
        pip --version
        tox --version
        echo
        pip list

    # Main test step is full test suite run on installed package with no
    # coverage
    - name: Test mytemplate python package
      run: |
        pushd mytemplate_pypkg
        tox -r -e nocoverage
        popd

    - name: Archive tested mytemplate distributions
      uses: actions/upload-artifact@v3
      with:
        name: tested-python-packages
        path: |
          mytemplate_pypkg/.tox/.pkg/dist/mytemplate-*.whl
          mytemplate_pypkg/.tox/.pkg/dist/mytemplate-*.tar.gz

    # Coverage is full test suite run on local clone so that coveralls
    # has nice output.  Generate html report to export as artifact.
    - name: Generate all coverage for coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # We want to preserve all individual coverage results as artifacts.
        # Therefore, save each of these to a unique file .coverage_<package name>
        # Save all in root of repo for later aggregation.
        pushd mytemplate_pypkg
        COVERAGE_FILE=../.coverage_mytemplate tox -r -e coverage
        popd
        # This aggregates into .coverage for coveralls
        tox -r -e aggregate,coveralls,report -- ./.coverage_*

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: |
            .coverage*
            htmlcov
